### ISSUE TITLE
360 Video Support

### ISSUE THREAD

**Issue by jtkeyva** [dariocavada/panorama_viewer#9]
Will/can this support 360 videos?

**Comment by dariocavada** [comment]
I created this package because the original one was not compatible with the latest versions of Flutter. If there are integrations that you would like to make, you can submit a pull request with the code to be corrected or added. Unfortunately, I don't have the time to add further features, but I am currently only maintaining the package for the latest versions of Flutter and dependencies of the component from any updated packages.

**Comment by jtkeyva** [comment]
got it thanks. i found a few that work ok

video_player_extra
video_360
vr_player

**Comment by dariocavada** [comment]
ok. there are alternatives.
so I close this issue.
